# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wunderlist' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wunderlist

  target 'WunderlistTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SwiftLint'

  target 'WunderlistUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
